language: python
python:
- '3.6'
install:
- pip install -r requirements.txt
script:
- export CONSUMER_KEY=$CONSUMER_KEY
- export CONSUMER_SECRET=$CONSUMER_SECRET
- export ACCESS_KEY=ACCESS_KEY
- export ACCESS_SECRET=ACCESS_SECRET
- python3 literallyp1/literallyp1.py

